-- ACCOUNT, ROLE, ACCOUNT_ROLE

CREATE TABLE ACCOUNT (
    USER_ID SERIAL PRIMARY KEY
    , USER_NAME VARCHAR (50) UNIQUE NOT NULL
    , PASSWORD VARCHAR (50) NOT NULL
    , EMAIL VARCHAR (500) UNIQUE NOT NULL
    , CREATED_ON TIMESTAMP NOT NULL
    , LAST_LOGIN TIMESTAMP
);

CREATE TABLE ROLE (
    ROLE_ID SERIAL PRIMARY KEY
    , ROLE_NAME VARCHAR (255) UNIQUE NOT NULL
);

CREATE TABLE ACCOUNT_ROLE (
    USER_ID INTEGER NOT NULL
    , ROLE_ID INTEGER NOT NULL
    , GRANT_DATE TIMESTAMP WITHOUT TIME ZONE
    , PRIMARY KEY (USER_ID, ROLE_ID)
    , CONSTRAINT ACCOUNT_ROLE_ROLE_ID_FKEY FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ROLE_ID) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
    , CONSTRAINT ACCOUNT_ROLE_USER_ID_FKEY FOREIGN KEY (USER_ID)
        REFERENCES ACCOUNT (USER_ID) MATCH SIMPLE ON
        UPDATE NO ACTION ON DELETE NO ACTION
);


insert into ACCOUNT values (1, '기승민', '0328', 'fsjki0328@naver.com', CURRENT_TIMESTAMP, null);


select * from account;

insert into role VALUES(1, '학생');

select * from role;

insert into account_role values (1, 1, CURRENT_TIMESTAMP);

select * from ACCOUNT_ROLE;


insert into account_role values (2, 1, CURRENT_TIMESTAMP);
